<font size=4 color='blue'>Copyright: 2021</font>

<font size=4 color='blue'>Author: Fernand B. Eloundou</font>
    
---------------------------------------------------------------------------------------------------
    
<font size=4 color='black'>File: RMSE_of_RLD_Simulations.ipynb</font>

----------------------------------------------------------------------------------------------------

In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

import pickle5 as pkl

In [2]:
# Open measured RLD data in control plot

with open('RLD_ctrl.pkl','rb') as f:
    measured_RLD_ctrl = pkl.load(f)

measured_rld = measured_RLD_ctrl.values
measured_rld

array([[ 3.36685095,  1.89385366,  1.26256911, ...,  1.47299729,
         1.26256911,  1.68342548],
       [ 0.94692683,  1.47299729,  2.10428184, ...,  0.84171274,
         1.26256911,  1.05214092],
       [ 1.3677832 ,  1.26256911,  1.15735501, ..., -1.        ,
         0.73649865, -1.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [3]:
# Read simulated RLD data in control plot

sim_ctrl = pd.read_csv('sim_data_ctrl.txt', header=None)
sim_rld = sim_ctrl.values
sim_rld

array([[0.7129, 0.997 , 1.0393, ..., 0.8813, 0.9419, 0.2563],
       [1.2005, 0.3363, 1.1219, ..., 0.7382, 0.932 , 0.5934],
       [0.9207, 0.2148, 0.8308, ..., 0.5055, 0.7547, 0.6773],
       ...,
       [0.1835, 0.0654, 0.2681, ..., 0.2518, 0.3335, 0.3342],
       [0.1161, 0.0046, 0.2757, ..., 0.2269, 0.2037, 0.1894],
       [0.0626, 0.    , 0.1663, ..., 0.0965, 0.0462, 0.1224]])

In [4]:
# Open measured RLD data in DL plot

with open('RLD_DL.pkl','rb') as f:
    measured_RLD_DL = pkl.load(f)
    
measured_rld_DL = measured_RLD_DL.values
measured_rld_DL

array([[ 1.05214092,  2.7355664 ,  2.31471003, ..., -1.        ,
        -1.        , -1.        ],
       [ 1.68342548,  1.89385366,  0.84171274, ...,  0.84171274,
         1.05214092,  1.05214092],
       [ 0.84171274,  1.15735501,  0.84171274, ...,  0.63128455,
         0.84171274,  0.63128455],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.374025  ,
         0.        ,  0.374025  ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.89537552],
       [ 0.        ,  2.68612656,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [5]:
# Read simulated RLD data in DL plot

sim_DL = pd.read_csv('sim_data_DL.txt', header=None)
sim_rld_DL = sim_DL.iloc[:,30:50].values
sim_rld_DL

array([[1.031 , 1.0981, 0.672 , ..., 0.6858, 0.7395, 0.52  ],
       [0.678 , 0.8775, 1.1179, ..., 0.544 , 0.7289, 0.7185],
       [0.4059, 0.5478, 0.9463, ..., 0.4879, 0.6569, 0.5641],
       ...,
       [0.2068, 0.2851, 0.3826, ..., 0.056 , 0.2168, 0.223 ],
       [0.1353, 0.1391, 0.4765, ..., 0.0223, 0.1218, 0.1593],
       [0.105 , 0.0988, 0.3199, ..., 0.0247, 0.0841, 0.0497]])

In [6]:
# RMSE CTRL 

rmse_ctrl = np.sqrt(sum(sum((sim_rld - measured_rld)**2))/measured_rld.size)
rmse_ctrl

0.9660197136878991

In [7]:
# Scatter index or normalized RMSE of two-dimension RLD in control plot
# scatter index < 1 means optimization is good

mean_measured_rld_ctrl = sum(sum(measured_rld))/measured_rld.size
scatter_index_ctrl = rmse_ctrl/mean_measured_rld_ctrl
scatter_index_ctrl

1.760379374847429

In [8]:
# RMSE DL

rmse_DL = np.sqrt(sum(sum((sim_rld_DL - measured_rld_DL)**2))/measured_rld_DL.size)
rmse_DL

1.1183382807217366

In [9]:
# Scatter index or normalized RMSE of two-dimension RLD in DL plot
# scatter index < 1 means optimization is good

mean_measured_rld_DL = sum(sum(measured_rld_DL))/measured_rld_DL.size
scatter_index_DL = rmse_DL/mean_measured_rld_DL
scatter_index_DL

1.5353675966757132

In [10]:
# R-squared

def total_variance(ytrue, mean_ytrue):
    tss = sum(sum((ytrue - mean_ytrue)**2))
    return tss


def residual_sse(ytrue, ypred):
    rss = sum(sum((ytrue - ypred)**2))
    return rss

In [11]:
# R_Squared ctrl opt

tss = total_variance(measured_rld, mean_measured_rld_ctrl) 
rss = residual_sse(measured_rld, sim_rld)
r_squared = (tss - rss)/tss

r_squared

0.019631894639189927

In [12]:
# R-squared DL

tss_DL = total_variance(measured_rld_DL, mean_measured_rld_DL) 
rss_DL = residual_sse(measured_rld_DL, sim_rld_DL)
r_squared_DL = (tss_DL - rss_DL)/tss_DL

r_squared_DL

-0.0003784634891860983

In [13]:
# Function to convert the 2D RLD data to 1D by averaging each row.

def one_dimension_rld(rld_data):
    
    rld_list = []
    for i in range(len(rld_data)):
        mean_rld = rld_data[i].mean()
        rld_list.append(mean_rld)
    return rld_list

In [14]:
# Measured and simulated 1D RLD in control and DL plots

measured_rld_1D_ctrl = np.array(one_dimension_rld(measured_rld))
sim_rld_1D_ctrl = np.array(one_dimension_rld(sim_rld))
measured_rld_1D_DL = np.array(one_dimension_rld(measured_rld_DL))
sim_rld_1D_DL = np.array(one_dimension_rld(sim_rld_DL))

In [15]:
# RMSE of one-dimension RLD in control plot

rmse_1D_ctrl = np.sqrt(sum((sim_rld_1D_ctrl - measured_rld_1D_ctrl)**2)/len(measured_rld_1D_ctrl))
rmse_1D_ctrl

0.2909937753507045

In [16]:
# Scatter index or normalized RMSE of one-dimension RLD in control plot
# scatter index < 1 means optimization is good

mean_rld_1D_ctrl = measured_rld_1D_ctrl.mean()
scatter_index_1D_ctrl = rmse_1D_ctrl/mean_rld_1D_ctrl
scatter_index_1D_ctrl

0.5302784540294243

In [17]:
# RMSE of one-dimension RLD in DL plot

rmse_1D_DL = np.sqrt(sum((sim_rld_1D_DL - measured_rld_1D_DL)**2)/len(measured_rld_1D_DL))
rmse_1D_DL

0.436020498037977

In [18]:
# Scatter index or normalized RMSE of one-dimension RLD in DL plot
# scatter index < 1 means optimization is good

mean_rld_1D_DL = measured_rld_1D_DL.mean()
scatter_index_1D_DL = rmse_1D_DL/mean_rld_1D_DL
scatter_index_1D_DL 

0.5986129203606221